### ISSUE TITLE
[PE-D][Tester C] [DG] Choice of colour scheme

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-1/tp#148]
![image.png](https://raw.githubusercontent.com/louisjoety/ped/main/files/3f217073-4254-42e9-8a4e-d3e1802aaf96.png)

Generally good use of diagrams but may consider using neutral colours or no colours as it works better on low contrast screen

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: louisjoety/ped#3

**Comment by jadenlimjc** [comment]
use colours to provide clear representation of activation bars and differentiation between each activation bar.
