### ISSUE TITLE
[PE-D][Tester C] [DG] Square boxes notation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#150]
![image.png](https://raw.githubusercontent.com/louisjoety/ped/main/files/e697684a-b0c1-4b34-9812-94d33c7eba48.png)

I recall in the lecture examples, the boxes are sharp edge boxes instead of rounded edges.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: louisjoety/ped#5

**Comment by jadenlimjc** [comment]
not specified on course website
