### ISSUE TITLE
[PE-D][Tester D] Uncaught exception when input `update 02 -deadline 12324rt /01/01/01`, `unknown flag:` where something should be printed afterwards

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#161]
![image.png](https://raw.githubusercontent.com/wongwh2002/ped/main/files/b8d031b9-7e05-4a81-9fb3-b55ac2a8018b.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: wongwh2002/ped#3

**Comment by jadenlimjc** [comment]
bug cannot be replicated.
