### ISSUE TITLE
[PE-D][Tester B] [EASInternship] Inconsistency in help message for sort

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#168]
For the sort command, the User Guide correctly states that the user should input the sorting flag with a dash '-'  

![image.png](https://raw.githubusercontent.com/isaacsaw25/ped/main/files/0da20dc0-4f4f-4826-8fc3-d57c499c995b.png)

However, in the help message, the dash is missing  

![image.png](https://raw.githubusercontent.com/isaacsaw25/ped/main/files/07d23204-02f1-4493-8427-7423e7014420.png)

This may lead to confusion, and I think it would be best to edit the help message.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: isaacsaw25/ped#2

**Comment by Toby-Yu** [comment]
Added dash in the help message
