### ISSUE TITLE
[PE-D][Tester C] [JAR] Sort function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#169]
![image.png](https://raw.githubusercontent.com/louisjoety/ped/main/files/ca6eaad9-b7a2-4d5a-aaee-f58fc80d3cd7.png)

Can I sort 2 at a time?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: louisjoety/ped#12

**Comment by Toby-Yu** [comment]
I will add description in UG and DG which clearly mention we can only sort by one field in each time.
