### ISSUE TITLE
[PE-D][Tester B] [EASInternsjip] Not enough example test cases provided

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#172]
![image.png](https://raw.githubusercontent.com/isaacsaw25/ped/main/files/d7a04b43-c96b-42be-b144-0c6e7b55fbc3.png)  

![image.png](https://raw.githubusercontent.com/isaacsaw25/ped/main/files/dcd5c7b4-fa9d-4870-bb35-ec749724bf79.png)

As a tester, I would like to have more example test cases to test out the features, but I find that there aren't sufficient that are provided. Perhaps it would be better to provide testers with more commands to add, so that the list is more populated?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: isaacsaw25/ped#3

**Comment by jadenlimjc** [comment]
added two erroneous test cases
