### ISSUE TITLE
[PE-D][Tester D] Manually changed data file (deadline entry), did not affect the program even after restarting.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-1/tp#195]
![image.png](https://raw.githubusercontent.com/wongwh2002/ped/main/files/90c88b28-71e4-4b58-ad90-7bc5b78c8f2b.png)

changed "No Deadlines set." to "no friends for me"

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: wongwh2002/ped#13

**Comment by jadenlimjc** [comment]
expected behaviour. of course its supposed to default to no deadlines set.
