### ISSUE TITLE
[PE-D][Tester C] [JAR] Favourites Function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-1/tp#200]
![image.png](https://raw.githubusercontent.com/louisjoety/ped/main/files/a1bb6708-5895-473c-956d-93126c703bb7.png)

Jar unable to load when `FAVOURITES` is changed to `S`

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: louisjoety/ped#22

**Comment by jadenlimjc** [comment]
fixed, if favourites term is changed will throw invalid line in file
